{{- if eq .Values.ibex.type "internal" -}}
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: "{{ template "nightingale.ibex" . }}"
  labels:
    app: ibex
    app.kubernetes.io/managed-by: Helm
    app.kubesphere.io/instance: ibex
    chart: ibex
    component: center
    heritage: Helm
    release: ibex
spec:
  replicas: {{ .Values.ibex.internal.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ibex
      app.kubesphere.io/instance: ibex
      release: ibex
  template:
    metadata:
      labels:
        app: ibex
        app.kubesphere.io/instance: ibex
        release: ibex
{{- if .Values.ibex.podAnnotations }}
{{ toYaml .Values.ibex.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args:
        - sh
        - -c
        - /app/ibex server
        env:
        - name: GIN_MODE
          value: release
        - name: TZ
          value: Asia/Shanghai
        image: {{ .Values.ibex.internal.image.repository }}:{{ .Values.ibex.internal.image.tag }}
        name: ibex
        ports:
        - containerPort: 10090
        - containerPort: 20090
{{- if .Values.ibex.internal.resources }}
        resources:
{{ toYaml .Values.ibex.internal.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /app/etc
          name: ibex-config
      restartPolicy: Always
      volumes:
        - name: ibex-config
          configMap:
            name: ibex-config
    {{- with .Values.ibex.internal.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ibex.internal.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.ibex.internal.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
